name: Build and Push Docker Images

on: [push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Shellcheck
      run: shellcheck bin/*

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull Docker Images
      run: |
        bin/docker_login.sh
        bin/docker_pull.sh
      env:
        GITHUB_USERNAME: mandrews
        GITHUB_DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_DOCKER_REGISTRY_TOKEN }}
    - name: Build Docker Images
      run: bin/docker_build.sh
    - name: Push Docker Images
      run: |
        bin/docker_login.sh
        bin/docker_push.sh
      env:
        GITHUB_USERNAME: mandrews
        GITHUB_DOCKER_REGISTRY_TOKEN: ${{ secrets.GITHUB_DOCKER_REGISTRY_TOKEN }}
